[book]
title = "Numbers in Rust"
description = "Learn the foundations of numbers as implemented in Rust"
authors = ["Matthew J Perez"]
language = "en"
multilingual = false
src = "src"


[output.html]
git-repository-url = "https://github.com/mattjperez/numbers-in-rust/tree/main"
edit-url-template = "https://github.com/mattjperez/numbers-in-rust/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-heirarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
